//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QEnergy.API.TextResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QEnergy.API.TextResources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Base_Accept {
            get {
                return ResourceManager.GetString("Base_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Base_Cancel {
            get {
                return ResourceManager.GetString("Base_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Base_Loading {
            get {
                return ResourceManager.GetString("Base_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found.
        /// </summary>
        public static string Base_NoResultFound {
            get {
                return ResourceManager.GetString("Base_NoResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Base_RequiredField {
            get {
                return ResourceManager.GetString("Base_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string Filter_Clean {
            get {
                return ResourceManager.GetString("Filter_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter_Filter {
            get {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Logout {
            get {
                return ResourceManager.GetString("Layout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password.
        /// </summary>
        public static string Login_RememberPassword {
            get {
                return ResourceManager.GetString("Login_RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Login_SignIn {
            get {
                return ResourceManager.GetString("Login_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string Pagination_First {
            get {
                return ResourceManager.GetString("Pagination_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Pagination_Last {
            get {
                return ResourceManager.GetString("Pagination_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Pagination_Next {
            get {
                return ResourceManager.GetString("Pagination_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Pagination_Previous {
            get {
                return ResourceManager.GetString("Pagination_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing [RECORD_MIN] to [RECORD_MAX] of [TOTAL_RECORDS] results.
        /// </summary>
        public static string Pagination_Text {
            get {
                return ResourceManager.GetString("Pagination_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string ProjectDealTypes_Asset {
            get {
                return ResourceManager.GetString("ProjectDealTypes_Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ProjectDealTypes_Share {
            get {
                return ResourceManager.GetString("ProjectDealTypes_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition date.
        /// </summary>
        public static string Projects_AcquisitionDate {
            get {
                return ResourceManager.GetString("Projects_AcquisitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string Projects_AddNew {
            get {
                return ResourceManager.GetString("Projects_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Projects_Company {
            get {
                return ResourceManager.GetString("Projects_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        public static string Projects_DateFrom {
            get {
                return ResourceManager.GetString("Projects_DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        public static string Projects_DateTo {
            get {
                return ResourceManager.GetString("Projects_DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal type.
        /// </summary>
        public static string Projects_DealType {
            get {
                return ResourceManager.GetString("Projects_DealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Projects_Delete {
            get {
                return ResourceManager.GetString("Projects_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Projects_Edit {
            get {
                return ResourceManager.GetString("Projects_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Projects_Group {
            get {
                return ResourceManager.GetString("Projects_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Projects_Id {
            get {
                return ResourceManager.GetString("Projects_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTG info.
        /// </summary>
        public static string Projects_Info {
            get {
                return ResourceManager.GetString("Projects_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kW.
        /// </summary>
        public static string Projects_Kw {
            get {
                return ResourceManager.GetString("Projects_Kw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months acquired.
        /// </summary>
        public static string Projects_MonthsAquired {
            get {
                return ResourceManager.GetString("Projects_MonthsAquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Projects_Name {
            get {
                return ResourceManager.GetString("Projects_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3l code.
        /// </summary>
        public static string Projects_Number3lCode {
            get {
                return ResourceManager.GetString("Projects_Number3lCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string Projects_ProjectName {
            get {
                return ResourceManager.GetString("Projects_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project number.
        /// </summary>
        public static string Projects_ProjectNumber {
            get {
                return ResourceManager.GetString("Projects_ProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project will be removed. Are you sure?.
        /// </summary>
        public static string Projects_RemoveProject {
            get {
                return ResourceManager.GetString("Projects_RemoveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Projects_Status {
            get {
                return ResourceManager.GetString("Projects_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTG Info.
        /// </summary>
        public static string Projects_WTGInfo {
            get {
                return ResourceManager.GetString("Projects_WTGInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTG numbers.
        /// </summary>
        public static string Projects_WTGNumbers {
            get {
                return ResourceManager.GetString("Projects_WTGNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProjectsList_Title {
            get {
                return ResourceManager.GetString("ProjectsList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquisition.
        /// </summary>
        public static string ProjectStatuses_Aquisition {
            get {
                return ResourceManager.GetString("ProjectStatuses_Aquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In development.
        /// </summary>
        public static string ProjectStatuses_InDevelopment {
            get {
                return ResourceManager.GetString("ProjectStatuses_InDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating.
        /// </summary>
        public static string ProjectStatuses_Operating {
            get {
                return ResourceManager.GetString("ProjectStatuses_Operating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Table_ColumnActions {
            get {
                return ResourceManager.GetString("Table_ColumnActions", resourceCulture);
            }
        }
    }
}
